name: nats
version: 0.1.0
description: NATS client for Dart language
author: Chaitanya Munukutla <chaitanya.m61292@gmail.com>
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  test: ^1.17.11
  logging: ^1.0.1
  mockito: ^5.0.15
  